name: Hannie
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # Thêm dòng này
  http: ^0.13.5
  provider: ^6.0.5
  qr_flutter: ^4.1.0  # Thêm package này để tạo mã QR
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1  # Thêm thư viện intl để định dạng ngày tháng

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

# Cấu hình flutter_native_splash đúng cách
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_image.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12:
    image: null
    color: "#ffffff"
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_image.png
    branding: null
  image_dark: assets/images/splash_image.png
  color_dark: "#ffffff"
  web: false

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 300
